### Get all users; 200
GET http://localhost:8081/api/users

### Get user by id; 200
GET http://localhost:8081/api/users/1

### Get user by id; 404
GET http://localhost:8081/api/users/999

### Get a users channels; 200
GET http://localhost:8081/api/users/1/channels

### Get a users channels; 204
GET http://localhost:8081/api/users/2/channels

### Get a users channels; 404
GET http://localhost:8081/api/users/999/channels

### Delete user by id; 204
// @no-cookie-jar
DELETE http://localhost:8081/api/users/1
Cookie: {{Cookie}}
X-XSRF-TOKEN: {{XSRF-TOKEN}}

### Update user by id; 200
// @no-cookie-jar
PUT http://localhost:8081/api/users/1
Content-Type: application/json
Accept: application/json
Cookie: {{Cookie}}
X-XSRF-TOKEN: {{XSRF-TOKEN}}

{
  "name": "User 1",
  "birthdate": "2018-01-01",
  "role": "Mod"
}

### Update user by id; 404
// @no-cookie-jar
PUT http://localhost:8081/api/users/999
Content-Type: application/json
Accept: application/json
Cookie: {{Cookie}}
X-XSRF-TOKEN: {{XSRF-TOKEN}}

{
  "name": "does not exist",
  "birthdate": "2018-01-01",
  "role": "Mod"
}

### Getting all users in XML
GET http://localhost:8081/api/users
Accept: application/xml
