spring:
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    profiles:
        active: prod # options: dev, prod
    messages:
        basename: templates/messages
server:
    port: 8081
