spring:
    datasource:
        url: jdbc:hsqldb:file:./db/kdGG;DB_CLOSE_DELAY=-1;hsqldb.lock_file=false
        driver-class-name: org.hsqldb.jdbc.JDBCDriver
        username: admin
        password: admin
    devtools:
        restart:
            enabled: true
            additional-paths: src/main/java
            additional-exclude: WEB-INF/**
    thymeleaf:
        cache: false
    sql:
        init:
            mode: always

logging:
    level:
        #        web: debug
        be.kdg.programming5: debug
