spring:
    mvc:
        hiddenmethod:
            filter:
                enabled: true
    profiles:
        active: prod # options: dev, prod
    messages:
        basename: templates/messages
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
server:
    port: 8081
