spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/kdgg
        driver-class-name: org.postgresql.Driver
        username: spring
        password: spring
    jpa:
        hibernate:
            ddl-auto: create
        database: POSTGRESQL
        show-sql: true
    devtools:
        restart:
            enabled: true
            additional-paths: src/main/java
            additional-exclude: WEB-INF/**
    thymeleaf:
        cache: false
    sql:
        init:
            mode: always
logging:
    level:
        #        web: debug
        be.kdg.programming5: debug
